var com = {
	"qmino":{
		"miredot":{
		},
	},
};
com.qmino.miredot.restApiSource = {
	"projectName":"app",
	"projectVersion":"unspecified",
	"projectTitle":"app-unspecified",
	"buildSystem":"gradle",
	"miredotVersion":"1.6.2",
	"miredotRevision":"f89b750ce8b9",
	"jsonDocEnabled":false,
	"jsonDocHidden":true,
	"singlePage":false,
	"hideLogoOnTop":false,
	"dateOfGeneration":"2016-02-10 18:48:17",
	"validLicense":true,
	"licenseErrorMessage":null,
	"licenseType":"FREE",
	"allowUsageTracking":true,
	"licenseHash":"3285398527620812232",
};

com.qmino.miredot.restApiSource.tos = {
	"org_metplus_curriculum_web_GenericAnswer_in":{
		"type":"complex",
		"name":"org_metplus_curriculum_web_GenericAnswer_in",
		"content":[
		],
	},
	"org_metplus_curriculum_web_GenericAnswer_out":{
		"type":"complex",
		"name":"org_metplus_curriculum_web_GenericAnswer_out",
		"content":[
		],
	},
	"org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__in":{
		"type":"complex",
		"name":"org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__in",
		"content":[
		],
	},
	"org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out":{
		"type":"complex",
		"name":"org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out",
		"content":[
		],
	},
	"org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__in":{
		"type":"complex",
		"name":"org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__in",
		"content":[
		],
	},
	"org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__out":{
		"type":"complex",
		"name":"org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__out",
		"content":[
		],
	},
	"org_springframework_web_multipart_MultipartFile_in":{
		"type":"complex",
		"name":"org_springframework_web_multipart_MultipartFile_in",
		"content":[
		],
	},
	"org_springframework_web_multipart_MultipartFile_out":{
		"type":"complex",
		"name":"org_springframework_web_multipart_MultipartFile_out",
		"content":[
		],
	},
	"org_metplus_curriculum_database_domain_Settings_in":{
		"type":"complex",
		"name":"org_metplus_curriculum_database_domain_Settings_in",
		"content":[
		],
	},
	"org_metplus_curriculum_database_domain_Settings_out":{
		"type":"complex",
		"name":"org_metplus_curriculum_database_domain_Settings_out",
		"content":[
		],
	},
	"org_springframework_http_ResponseEntity_java_lang_Object__in":{
		"type":"complex",
		"name":"org_springframework_http_ResponseEntity_java_lang_Object__in",
		"content":[
		],
	},
	"org_springframework_http_ResponseEntity_java_lang_Object__out":{
		"type":"complex",
		"name":"org_springframework_http_ResponseEntity_java_lang_Object__out",
		"content":[
		],
	},
};
com.qmino.miredot.restApiSource.enums = {
	"org_springframework_http_HttpStatus":{
		"type":"enum",
		"name":"org.springframework.http.HttpStatus",
		"values":[
			{
				"name":"CONTINUE",
				"comment":null,
			},
			{
				"name":"SWITCHING_PROTOCOLS",
				"comment":null,
			},
			{
				"name":"PROCESSING",
				"comment":null,
			},
			{
				"name":"CHECKPOINT",
				"comment":null,
			},
			{
				"name":"OK",
				"comment":null,
			},
			{
				"name":"CREATED",
				"comment":null,
			},
			{
				"name":"ACCEPTED",
				"comment":null,
			},
			{
				"name":"NON_AUTHORITATIVE_INFORMATION",
				"comment":null,
			},
			{
				"name":"NO_CONTENT",
				"comment":null,
			},
			{
				"name":"RESET_CONTENT",
				"comment":null,
			},
			{
				"name":"PARTIAL_CONTENT",
				"comment":null,
			},
			{
				"name":"MULTI_STATUS",
				"comment":null,
			},
			{
				"name":"ALREADY_REPORTED",
				"comment":null,
			},
			{
				"name":"IM_USED",
				"comment":null,
			},
			{
				"name":"MULTIPLE_CHOICES",
				"comment":null,
			},
			{
				"name":"MOVED_PERMANENTLY",
				"comment":null,
			},
			{
				"name":"FOUND",
				"comment":null,
			},
			{
				"name":"MOVED_TEMPORARILY",
				"comment":null,
			},
			{
				"name":"SEE_OTHER",
				"comment":null,
			},
			{
				"name":"NOT_MODIFIED",
				"comment":null,
			},
			{
				"name":"USE_PROXY",
				"comment":null,
			},
			{
				"name":"TEMPORARY_REDIRECT",
				"comment":null,
			},
			{
				"name":"PERMANENT_REDIRECT",
				"comment":null,
			},
			{
				"name":"BAD_REQUEST",
				"comment":null,
			},
			{
				"name":"UNAUTHORIZED",
				"comment":null,
			},
			{
				"name":"PAYMENT_REQUIRED",
				"comment":null,
			},
			{
				"name":"FORBIDDEN",
				"comment":null,
			},
			{
				"name":"NOT_FOUND",
				"comment":null,
			},
			{
				"name":"METHOD_NOT_ALLOWED",
				"comment":null,
			},
			{
				"name":"NOT_ACCEPTABLE",
				"comment":null,
			},
			{
				"name":"PROXY_AUTHENTICATION_REQUIRED",
				"comment":null,
			},
			{
				"name":"REQUEST_TIMEOUT",
				"comment":null,
			},
			{
				"name":"CONFLICT",
				"comment":null,
			},
			{
				"name":"GONE",
				"comment":null,
			},
			{
				"name":"LENGTH_REQUIRED",
				"comment":null,
			},
			{
				"name":"PRECONDITION_FAILED",
				"comment":null,
			},
			{
				"name":"PAYLOAD_TOO_LARGE",
				"comment":null,
			},
			{
				"name":"REQUEST_ENTITY_TOO_LARGE",
				"comment":null,
			},
			{
				"name":"URI_TOO_LONG",
				"comment":null,
			},
			{
				"name":"REQUEST_URI_TOO_LONG",
				"comment":null,
			},
			{
				"name":"UNSUPPORTED_MEDIA_TYPE",
				"comment":null,
			},
			{
				"name":"REQUESTED_RANGE_NOT_SATISFIABLE",
				"comment":null,
			},
			{
				"name":"EXPECTATION_FAILED",
				"comment":null,
			},
			{
				"name":"I_AM_A_TEAPOT",
				"comment":null,
			},
			{
				"name":"INSUFFICIENT_SPACE_ON_RESOURCE",
				"comment":null,
			},
			{
				"name":"METHOD_FAILURE",
				"comment":null,
			},
			{
				"name":"DESTINATION_LOCKED",
				"comment":null,
			},
			{
				"name":"UNPROCESSABLE_ENTITY",
				"comment":null,
			},
			{
				"name":"LOCKED",
				"comment":null,
			},
			{
				"name":"FAILED_DEPENDENCY",
				"comment":null,
			},
			{
				"name":"UPGRADE_REQUIRED",
				"comment":null,
			},
			{
				"name":"PRECONDITION_REQUIRED",
				"comment":null,
			},
			{
				"name":"TOO_MANY_REQUESTS",
				"comment":null,
			},
			{
				"name":"REQUEST_HEADER_FIELDS_TOO_LARGE",
				"comment":null,
			},
			{
				"name":"INTERNAL_SERVER_ERROR",
				"comment":null,
			},
			{
				"name":"NOT_IMPLEMENTED",
				"comment":null,
			},
			{
				"name":"BAD_GATEWAY",
				"comment":null,
			},
			{
				"name":"SERVICE_UNAVAILABLE",
				"comment":null,
			},
			{
				"name":"GATEWAY_TIMEOUT",
				"comment":null,
			},
			{
				"name":"HTTP_VERSION_NOT_SUPPORTED",
				"comment":null,
			},
			{
				"name":"VARIANT_ALSO_NEGOTIATES",
				"comment":null,
			},
			{
				"name":"INSUFFICIENT_STORAGE",
				"comment":null,
			},
			{
				"name":"LOOP_DETECTED",
				"comment":null,
			},
			{
				"name":"BANDWIDTH_LIMIT_EXCEEDED",
				"comment":null,
			},
			{
				"name":"NOT_EXTENDED",
				"comment":null,
			},
			{
				"name":"NETWORK_AUTHENTICATION_REQUIRED",
				"comment":null,
			},
		],
	},
	"org_metplus_curriculum_web_ResultCodes":{
		"type":"enum",
		"name":"org.metplus.curriculum.web.ResultCodes",
		"values":[
			{
				"name":"SUCCESS",
				"comment":null,
			},
			{
				"name":"ACCESS_DENIED",
				"comment":null,
			},
			{
				"name":"FATAL_ERROR",
				"comment":null,
			},
			{
				"name":"RESUME_NOT_FOUND",
				"comment":null,
			},
		],
	},
};
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_in"].content = [
	{
		"name":"message",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"resultCode",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["org_metplus_curriculum_web_ResultCodes"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_in"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_out"].content = [
	{
		"name":"message",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"resultCode",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["org_metplus_curriculum_web_ResultCodes"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_out"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__in"].content = [
];
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__in"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out"].content = [
	{
		"name":"headers",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"object",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"body",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusCode",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["org_springframework_http_HttpStatus"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__in"].content = [
];
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__in"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__out"].content = [
	{
		"name":"headers",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"object",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"body",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_web_GenericAnswer_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusCode",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["org_springframework_http_HttpStatus"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__out"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_in"].content = [
];
com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_in"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_out"].content = [
	{
		"name":"name",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"bytes",
		"comment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"byte",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"empty",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"size",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"inputStream",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.io.InputStream",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"contentType",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"originalFilename",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_out"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_in"].content = [
	{
		"name":"id",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_in"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_out"].content = [
	{
		"name":"id",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_out"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_out"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__in"].content = [
];
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__in"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__out"].content = [
	{
		"name":"headers",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"object",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"body",
		"comment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"object",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusCode",
		"comment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["org_springframework_http_HttpStatus"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__out"].ordered = "false";
com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__out"].comment = null;
com.qmino.miredot.restApiSource.interfaces = [
	{
		"beschrijving":"",
		"url":"/api/v1//curriculum/{userId}",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_java_lang_Object__out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1119905985",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"userId",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/api/v1//admin/settings",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-273747639",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_metplus_curriculum_database_domain_Settings_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/api/v1//admin/settings",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_database_domain_Settings__out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"174973169",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/api/v1//curriculum/upload",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_springframework_http_ResponseEntity_org_metplus_curriculum_web_GenericAnswer__out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"390548841",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
				{
					"name":"userId",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"QUERY",
				},
				{
					"name":"name",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"QUERY",
				},
				{
					"name":"file",
					"typeValue":com.qmino.miredot.restApiSource.tos["org_springframework_web_multipart_MultipartFile_in"],
					"comment":null,
					"jaxrs":"QUERY",
				},
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
];
com.qmino.miredot.projectWarnings = [
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_PRODUCES",
		"description":"Interface returns a result, but does not specify a Produces value.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_EXCEPTION_DOCUMENTATION",
		"description":"Exception thrown by method has no comment",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_PRODUCES",
		"description":"Interface returns a result, but does not specify a Produces value.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_CONSUMES",
		"description":"Interface specifies a JAXRS-BODY parameter, but does not specify a Consumes value.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"REST_UNMAPPED_EXCEPTION",
		"description":"Exception is thrown by interface specification, but is not mapped in the MireDot configuration. As such, the return errorcode can not be documented properly.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_PRODUCES",
		"description":"Interface returns a result, but does not specify a Produces value.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_PRODUCES",
		"description":"Interface returns a result, but does not specify a Produces value.",
		"failedBuild":"false",
		"interface":null,
		"entity":null,
	},
];
com.qmino.miredot.processErrors = [
];

